# docker compose multi-build file
volumes:
  dist:

x-configuration: &CONFIGURATION
  volumes:
    - .:/Source:ro
    - dist:/dist
  working_dir: /Build
  command: bash -c "${COMPOSE_COMMAND-
    cmake -G Ninja /Source;
    ninja;
    ninja install;
    ninja run;
    cp ../Source/demo.zip ../demo.zip;
    cp ../Source/demoMultipleFiles.zip ../demoMultipleFiles.zip;
    cp ../Source/testsuite.tar.xz ../testsuite.tar.xz;
    cp ../Source/decompressor.cpp ../decompressor.cpp && cp ../Source/demo.zip ../demo.zip;
    ctest -j 6 --timeout 10;}
    ${COMPOSE_APPEND- }"

x-platforms: &PLATFORMS
  platforms:
    - "linux/amd64"
    - "linux/arm64"

services:

  ubuntu_24.04:
    platform: ${PLATFORM}
    build:
      context: docker/ubuntu/
      tags:
        - "kevdillman/ubuntu:latest"
      <<: *PLATFORMS
      args:
        TAG: "24.04"
    environment:
      - PLATFORM=ubuntu_24.04
    <<: *CONFIGURATION

  ubuntu_23.10:
    platform: ${PLATFORM}
    build:
      context: docker/ubuntu/
      <<: *PLATFORMS
      args:
        TAG: "23.10"
    environment:
      - PLATFORM=ubuntu_23.10
    <<: *CONFIGURATION

  ubuntu_22.04:
    platform: ${PLATFORM}
    build:
      context: docker/ubuntu/
      <<: *PLATFORMS
      args:
        TAG: "22.04"
    environment:
      - PLATFORM=ubuntu_22.04
    <<: *CONFIGURATION

  fedora_41:
    platform: ${PLATFORM}
    build:
      context: docker/fedora/
      <<: *PLATFORMS
      args:
        TAG: "41"
    environment:
      - PLATFORM=fedora_41
    <<: *CONFIGURATION

  fedora_40:
    platform: ${PLATFORM}
    build:
      context: docker/fedora/
      <<: *PLATFORMS
      args:
        TAG: "40"
    environment:
      - PLATFORM=fedora_40
    <<: *CONFIGURATION

  fedora_39:
    platform: ${PLATFORM}
    build:
      context: docker/fedora/
      <<: *PLATFORMS
      args:
        TAG: "39"
    environment:
      - PLATFORM=fedora_39
    <<: *CONFIGURATION

  opensuse_15.5:
    platform: ${PLATFORM}
    build:
      context: docker/openSUSE/
      <<: *PLATFORMS
      args:
        TAG: "15.5"
    environment:
      - PLATFORM=opensuse_15.5
    <<: *CONFIGURATION
