---
name: Build

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{matrix.os}}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: Setup Linux packages
        shell: bash
        run:
          sudo apt-get install ninja-build libarchive-dev
        if: runner.os == 'Linux'

      - name: Setup MacOS packages
        shell: bash
        run:
          brew install ninja libarchive-dev
        if: runner.os == 'macOS'

      #- name: Setup Windows packages
      #  shell: bash
      #  run:

      #  if: runner.os == 'Windows'

      - name: CMake Setup
        working-directory: build
        shell: bash
        run: |
          cmake .. -G Ninja
