---
name: Build

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{matrix.os}}
    timeout-minutes: 10

      - name: Checkout Repository
        uses: actions/checkout@v4
