---
name: Fedora Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: kevdillman/fedora:41
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: CMake Setup
        working-directory: build
        shell: bash
        run: |
          cmake .. -G Ninja

      - name: Build
        working-directory: build
        shell: bash
        run: |
          cmake --build . --config Release --target all
      - uses: actions/upload-artifact@v4
        with:
          name: Executable-fedora41
          path: |
            build/decompressor

      - name: Install
        working-directory: build
        shell: bash
        run: |
          cmake --build . --config Release --target install/strip
